name: Python Workflow with Ubuntu-dependencies

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Clone repository
      - name: Clone repository
        uses: actions/checkout@v3
      # 3. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 4. Install dependencies with pip
      - name: Install dependencies with pip
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --upgrade

      # 5. Run tests
      #- name: Run tests
      #  run: pytest
      - name: run
        env:
          MYSECRET: $ {{ secrets.MYSECRET }}
        run: |
          python3 main.py